repos:
    - repo: https://gitlab.com/pycqa/flake8
      rev: "3.9.2"
      hooks:
          - id: flake8
    - repo: https://github.com/psf/black
      rev: 21.5b1
      hooks:
          - id: black
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.5.0
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v0.790"
      hooks:
          - id: mypy
            args: [--no-strict-optional, --ignore-missing-imports]
            additional_dependencies:
                - sqlalchemy-stubs
                - git+https://github.com/ssfdust/flask-sqlalchemy-stubs.git

    - repo: https://github.com/PyCQA/bandit
      rev: "1.7.0"
      hooks:
          - id: bandit
    - repo: https://github.com/PyCQA/prospector
      rev: "1.3.1"
      hooks:
          - id: prospector
            args: [-A]
            additional_dependencies:
                - "flask"
                - "sqlalchemy"
                - "flask_sqlalchemy"
                - "requests"
