# fly.toml app configuration file generated for votey-bot on 2023-05-25T12:55:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "votey-bot"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
